<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>de.redstonecloud</groupId>
    <artifactId>bridge</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <version.waterdogpe>2.0.3-SNAPSHOT</version.waterdogpe>
        <version.powernukkitx>nightly-SNAPSHOT</version.powernukkitx>
        <version.nukkit>1.0-SNAPSHOT</version.nukkit>
    </properties>

    <repositories>
        <repository>
            <id>waterdogpe-releases</id>
            <url>https://repo.waterdog.dev/releases</url>
        </repository>
        <repository>
            <id>waterdogpe-snapshots</id>
            <url>https://repo.waterdog.dev/snapshots</url>
        </repository>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
        <repository>
            <id>opencollab-snapshots</id>
            <url>https://repo.opencollab.dev/maven-snapshots/</url>
        </repository>
        <repository>
            <id>opencollab-releases</id>
            <url>https://repo.opencollab.dev/maven-releases/</url>
        </repository>
        <repository>
            <id>okaeri</id>
            <url>https://storehouse.okaeri.eu/repository/maven-public/</url>
        </repository>
        <repository>
            <id>lpmc-redstonecloud</id>
            <url>https://repo.lostplacemc.eu/redstonecloud</url>
        </repository>
        <repository>
            <id>pnx-releases</id>
            <url>https://repo.powernukkitx.org/releases</url>
        </repository>
    </repositories>

    <distributionManagement>
        <repository>
            <id>lpmc-redstonecloud</id>
            <url>https://repo.lostplacemc.eu/redstonecloud</url>
        </repository>
    </distributionManagement>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.34</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.powernukkitx</groupId>
            <artifactId>server</artifactId>
            <version>${version.powernukkitx}</version>
            <scope>provided</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.cloudburstmc.netty</groupId>
                    <artifactId>netty-transport-raknet</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>net.daporkchop</groupId>
                    <artifactId>leveldb-mcpe-jni</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>dev.waterdog.waterdogpe</groupId>
            <artifactId>waterdog</artifactId>
            <version>${version.waterdogpe}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>cn.nukkit</groupId>
            <artifactId>nukkit</artifactId>
            <version>${version.nukkit}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>de.redstonecloud</groupId>
            <artifactId>api</artifactId>
            <version>1.0.0-SNAPSHOT</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.2.4</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <transformers>
                        <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                    </transformers>
                    <outputFile>target\${project.artifactId}-${project.version}-shaded.jar</outputFile>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
